config/routes.rb
Rails.application.routes.draw do
 get "/static_pages/:page", to: "static_pages#show", as: "static_pages"
 get "/signup", to: "users#new"
 root "static_pages#show", page: "home"
 post "/signup", to: "users#create"
 get "/login", to: "sessions#new"
 post "/login", to: "sessions#create"
 delete "/logout", to: "sessions#destroy"

 resources :users
 resources :account_activations, only: [:edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  enum sex: %i(male female).freeze
  LIST_PERMIT_USER = %i(name email password password_confirmation sex).freeze
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  attr_reader :remember_token
  attr_accessor :activation_token

  validates :name,  presence: true,
   length: {maximum: Settings.user_model.name_max}
  validates :email, presence: true,
   length: {maximum: Settings.user_model.email_max},
   format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true, allow_blank: true,
   length: {minimum: Settings.user_model.password_min}

  has_secure_password

  before_save :downcase_email
  before_create :create_activation_digest

  scope :activated, ->{where activated: true}

  class << self
    def digest string
      cost =
        if ActiveModel::SecurePassword.min_cost
          BCrypt::Engine::MIN_COST
        else
          BCrypt::Engine.cost
        end
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    @remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def forget
    update_attributes remember_digest: nil
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false if digest.blank?
    BCrypt::Password.new(digest).is_password? token
  end

  def current_user? current_user
    self == current_user
  end

  def activate
    update_attributes activated: true, activated_at: Time.zone.now
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  private

  def downcase_email
    email.downcase!
  end

  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest activation_token
  end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
  def edit
    user = User.find_by mail: params[:email]
    if user && !user.activated? && user.authenticated?(:activation, params[:id])
      success user
    else
      unsuccess
    end
  end

  private

  def success user
    user.activate
    log_in user
    flash[:success] = t "controller.users.activated"
    redirect_to user
  end

  def unsuccess
    flash[:danger] = t "controller.users.invalid_activate"
    redirect_to root_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params_sessions(:email)

    if user && user.authenticate(params_sessions :password)
      if user.activated?
        success user
      else
        activated_fail
      end

    else
      unsuccess
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

  private

  def success user
    log_in user
    params_sessions(:remember_me) == "1" ? remember(user) : forget(user)
    redirect_back_or user
  end

  def unsuccess
    flash[:danger] = t "controller.users.invalid"
    render :new
  end

  def activated_fail
    flash[:warning] = t "controller.users.activated_fail"
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def show
    if valid_page? && check_page?
      render "static_pages/#{params[:page]}"
    else
      render file: "public/404.html", status: :not_found
    end
  end

  private
  def valid_page?
    File.exist? Pathname.new(Rails.root + "app/views/static_pages/#{params[:page]}.html.erb")
  end

  def check_page?
    check_list = %w(home about help contact)
    check_list.include? "#{params[:page]}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i(index edit update destroy)
  before_action :find_user, only: %i(edit show update destroy)
  before_action :correct_user, only: %i(edit update)
  before_action :admin_user, only: %i(destroy)

  def index
    @users = User.activated.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      @user.send_activation_email
      flash[:info] = t "controller.users.check_mail"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    return if @user
    redirect_to root_path && return unless user.activated?
    flash[:danger] = t "controller.users.danger"
  end

  def edit; end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "controller.users.update"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t "controller.users.destroy"
      redirect_to @user
    else
      flash[:danger] = t "controller.user.destroy_error"
      redirect_to users_path
    end
  end

  private

  def user_params
    params.require(:user).permit User::LIST_PERMIT_USER
  end

  def correct_user
    redirect_to root_path unless @user.current_user? current_user
  end

  def logged_in_user
    return if logged_in?
    store_location
    flash[:danger] = t "controller.users.pls"
    redirect_to login_path
  end

  def admin_user
    redirect_to root_path unless current_user.admin?
  end

  def find_user
    @user = User.find_by id: params[:id]

    return if @user
    flash[:danger] = t "controller.users.must_login"
    redirect_to login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t ".base_title"
    title = page_title
    page_title.empty? ? base_title : title + " | " + base_title
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def remember user
    user.remember
    cookies_signed user
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by id: user_id
    elsif user_id_cookies = cookies.signed[:user_id]
      user = User.find_by id: user_id_cookies
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    current_user.present?
  end

  def forget user
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end

  def log_out
    forget current_user
    session.delete :user_id
    @current_user = nil
  end

  def cookies_signed user
    cookies.permanent.signed[:user_id] = user.id
  end

  def params_sessions param
    params[:session][param]
  end

  def redirect_back_or default
    redirect_to session[:forwarding_url] || default
    session.delete :forwarding_url
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, options = {size: 80}
    gravatar_id = Digest::MD5.hexdigest user.email.downcase
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end

  def sex_choice
    User.sexes.keys.map{|key| [t("users.new.sex.#{key}"), key]}
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small><%= t(".intro",
    RoR: "http://www.railstutorial.org/",
    MH: "http://www.michaelhartl.com/").html_safe %></small>
  <nav>
    <ul>
      <li><%= link_to t(".about"), static_pages_path(:about) %></li>
      <li><%= link_to t(".contact"), static_pages_path(:contact) %></li>
      <li><a href="http://news.railstutorial.org/"><%=t(".new")%></a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".logo"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".home"), root_path %></li>
        <li><%= link_to t(".help"), static_pages_path(:help) %></li>
        <% if logged_in? %>
          <li><%= link_to t(".users"), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t".acc"%> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), current_user %></li>
              <li><%= link_to t(".settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".login"), login_path %></li>
        <% end %>

      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", media: "all",
 "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug params if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if users.errors.any? %>
  <div class="error_explanation">
    <div class="alert alert-danger">
      <%= t ".count_error"%> <%= pluralize users.errors.count, t(".error") %>.
    </div>
    <ul>
    <% users.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".heading" %></h1>
<p>
 <%= t(".content",
  home: "http://www.railstutorial.org/",
  book: "http://www.railstutorial.org/book",
  screencast_series: "http://screencasts.railstutorial.org/",
  RoR: "http://rubyonrails.org/").html_safe %>
</p>

app/views/static_pages/contact.html.erb
<%= provide :title, t(".title") %>
<h1><%= t ".heading" %></h1>
<p>
 <%= t(".content", contact: "http://www.railstutorial.org/contact").html_safe %>
</p>

app/views/static_pages/help.html.erb
<%= provide :title, t(".title") %>
<h1><%= t ".heading" %></h1><p>
 <%= t(".content",
  help: "http://www.railstutorial.org/help",
  book: "http://www.railstutorial.org/book").html_safe %>
</p>

app/views/static_pages/home.html.erb
<% provide :title, t(".title") %>
<div class="center jumbotron">
 <h1><%= t ".heading" %></h1>
  <p>
   <%= t(".content", home: "http://www.railstutorial.org/").html_safe %>
  </p>
 <%= link_to t(".signup"), signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails logo"),
 "http://rubyonrails.org/" %>

app/views/users/_form.html.erb
<%= form_for user do |f| %>
  <%= render "shared/error_messages", users: f.object%>

  <%= f.label :name, t(".name") %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, t(".email") %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password, t(".password") %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, t(".confirm") %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.label :sex, t(".t_sex") %>
   <%= f.select :sex, sex_choice %>

  <%= f.submit t(".create"), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !user.current_user?(current_user) %> |
    <%= link_to t(".delete"), user, method: :delete, data: {confirm: t(".sure")} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".save") %>
<h1><%= t".heading" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form", user: @user %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <%= link_to t(".change"), "http://gravatar.com/emails", target:"_blank" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= provide :title, t(".title") %>
<h1><%= t".title" %></h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide :title, t(".title") %>
<h1><%t ".heading"%></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: signup_path do |f| %>
      <%= render "shared/error_messages", users: f.object%>

      <%= f.label :name, t(".name") %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email, t(".email") %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password, t(".password") %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, t(".confirm") %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.label :sex, t(".t_sex") %>
      <%= f.select :sex, sex_choice %>

      <%= f.submit t(".create"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name%>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>